DROP TABLE IF EXISTS TBL_CUSTOMERS;
  
CREATE TABLE TBL_CUSTOMERS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  first_name VARCHAR(250) NOT NULL,
  last_name VARCHAR(250) NOT NULL,
  email VARCHAR(250) DEFAULT NULL
);

DROP TABLE IF EXISTS TBL_PRODUCTS;
  
CREATE TABLE TBL_PRODUCTS (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
  description VARCHAR(250) NOT NULL,
  id_tbl_customers INT
);

ALTER TABLE TBL_PRODUCTS ADD FOREIGN KEY (id_tbl_customers) REFERENCES TBL_CUSTOMERS(id);